/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	inputs  calculator_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, calc_prog, calc_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("enter two nubers:");
	scanf("%f%f",&(calculator_1_arg.a),&(calculator_1_arg.b));
	printf("enter operator u want to perform:");
	scanf(" %c",&(calculator_1_arg.op));

	result_1 = calculator_1(&calculator_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("result:%f\n",*result_1);	
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
exit (0);
}
