/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "example.h"
#include<stdio.h>
#include<string.h>
#include<math.h>

int *
fact_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result_1=1;

	/*
	 * insert server code here
	 */
	int i;
	for(i=(*argp);i>0;i--)
		result_1 *=i;

	return &result_1;
}

double *
power_1_svc(doubles *argp, struct svc_req *rqstp)
{
	static int result_2;

	/*
	 * insert server code here
	 */
	result_2= (int)pow((argp->a),(argp->b));
	//result_2=(argp->a)+(argp->b);

	return (double *)&result_2;
}

char **
strconc_1_svc(strings *argp, struct svc_req *rqstp)
{
	static char * result_3;

	/*
	 * insert server code here
	 */
	result_3= strcat((argp->dst),(argp->src));

	return &result_3;
}
