/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct s {
	int a;
	int b;
};
typedef struct s s;

#define add_prog 0x01234567
#define add_vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(s *, CLIENT *);
extern  int * add_1_svc(s *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_s (XDR *, s*);

#else /* K&R C */
extern bool_t xdr_s ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
