/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fctorial_1_svc(s *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int ans=1;
	int i;
	for(i=1;i<=(argp->n);i++)
	{
		ans=ans*i;
	}
	result=ans;
	printf("%d! = %d\n",(argp->n),ans);
	return &result;
}
